name: Claude Code

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  claude:
    runs-on: ubuntu-latest
    if: github.event.issue.user.login == github.repository_owner || github.event.comment.user.login == github.repository_owner
    steps:
      - name: Claude Code
        uses: anthropics/claude-code-action@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}